# Generated by Django 3.0.4 on 2020-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='photo',
            field=models.ImageField(blank=True, upload_to='class'),
        ),
    ]
