# Generated by Django 3.0.5 on 2020-05-27 18:59

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classanswer',
            name='inClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anw_class', to='firstApp.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutor_photo',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='tutor'),
        ),
    ]
