# Generated by Django 3.0.4 on 2020-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='on_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
