# Generated by Django 3.0.4 on 2020-05-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='in_max',
            field=models.PositiveIntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='in_min',
            field=models.PositiveIntegerField(blank=True, default='1', null=True),
        ),
    ]
