# Generated by Django 3.0.5 on 2020-04-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parentArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Area')),
            ],
        ),
    ]
