# Generated by Django 3.0.4 on 2020-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200925_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sale_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
