# Generated by Django 3.0.5 on 2020-04-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
