# Generated by Django 3.0.5 on 2020-04-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='teacher',
            new_name='tutor',
        ),
        migrations.AddField(
            model_name='classes',
            name='cateId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Category'),
        ),
    ]
