# Generated by Django 3.0.5 on 2020-04-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_detailarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
