# Generated by Django 3.0.5 on 2020-05-31 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200531_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='firstApp.ClassDate'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='inClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='firstApp.Class'),
        ),
    ]
