# Generated by Django 3.0.4 on 2020-11-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20201101_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'permissions': [('can_permit', 'Can permit')]},
        ),
    ]
