# Generated by Django 3.0.4 on 2020-05-05 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200506_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='in_max',
            field=models.PositiveIntegerField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='in_min',
            field=models.PositiveIntegerField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_blog',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_insta',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_photo',
            field=models.ImageField(default='', upload_to='tutor'),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_youtube',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 16, 27, 4, 872990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 16, 27, 4, 817009, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('inClass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edu_class', to='firstApp.Class')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='firstApp.State')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inClass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_class', to='firstApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inClass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certi_class', to='firstApp.Class')),
            ],
        ),
    ]
