# Generated by Django 3.0.5 on 2020-04-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20200421_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
