# Generated by Django 3.0.5 on 2020-04-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20200426_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
    ]
