# Generated by Django 3.0.5 on 2020-05-09 17:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20200509_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 7, 26, 342181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 7, 26, 216476, tzinfo=utc)),
        ),
    ]
