# Generated by Django 3.1 on 2020-11-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_category_category_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classdate',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_user',
        ),
    ]
