# Generated by Django 3.0.5 on 2020-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20201003_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
