# Generated by Django 3.0.5 on 2020-05-27 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='profile',
        ),
        migrations.AddField(
            model_name='class',
            name='like_user',
            field=models.ManyToManyField(related_name='like_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
