# Generated by Django 3.0.5 on 2020-10-03 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstApp', '0005_post_no_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_recommend_user',
            field=models.ManyToManyField(related_name='no_recommend_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='recommend_user',
            field=models.ManyToManyField(related_name='recommend_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
