# Generated by Django 3.0.5 on 2020-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20201019_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남자'), ('W', '여자')], max_length=80, null=True),
        ),
    ]
