# Generated by Django 3.0.5 on 2020-05-09 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20200510_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='classtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 19, 46, 3, 337955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 19, 46, 3, 212329, tzinfo=utc)),
        ),
    ]
