# Generated by Django 3.0.5 on 2020-10-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20201003_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sale_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
