# Generated by Django 3.0.5 on 2020-05-10 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_auto_20200510_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='date',
            new_name='classdate',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='classtitle',
        ),
        migrations.AddField(
            model_name='apply',
            name='inClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_class', to='firstApp.Class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 10, 48, 51, 102061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 10, 48, 50, 980401, tzinfo=utc)),
        ),
    ]
