# Generated by Django 3.0.5 on 2020-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_auto_20201019_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_categories',
            field=models.CharField(blank=True, choices=[('art', '미술,공예'), ('ent', '음악,댄스'), ('design', '디자인,개발'), ('career', '커리어'), ('lang', '언어'), ('beauty', '뷰티'), ('cooking', '요리,베이킹'), ('etc', '기타')], max_length=255, null=True),
        ),
    ]
