# Generated by Django 3.0.5 on 2020-05-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200506_0012'),
        ('firstApp', '0003_auto_20200506_0127'),
        ('firstApp', '0008_auto_20200506_0113'),
        ('firstApp', '0008_auto_20200510_1949'),
    ]

    operations = [
    ]
