# Generated by Django 3.0.5 on 2020-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_profile_model_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='model_categories',
        ),
        migrations.AddField(
            model_name='profile',
            name='model_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='model_categories', to='firstApp.Category'),
        ),
    ]
