# Generated by Django 3.0.5 on 2020-05-11 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_merge_20200511_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='classdate',
        ),
        migrations.AddField(
            model_name='apply',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_date', to='firstApp.ClassDate'),
        ),
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 38, 5, 255315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 38, 5, 253321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 38, 5, 130648, tzinfo=utc)),
        ),
    ]
