# Generated by Django 3.0.5 on 2020-05-11 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_auto_20200511_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='inClass',
        ),
        migrations.AddField(
            model_name='apply',
            name='classtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Class'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.ClassDate'),
        ),
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 18, 7, 614444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 18, 7, 495763, tzinfo=utc)),
        ),
    ]
