# Generated by Django 3.0.5 on 2020-05-11 15:21

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_auto_20200512_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 21, 20, 322051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 15, 21, 20, 197385, tzinfo=utc)),
        ),
    ]
