# Generated by Django 3.0.4 on 2020-05-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200519_0003'),
        ('firstApp', '0013_auto_20200512_0025'),
        ('firstApp', '0003_auto_20200512_1502'),
    ]

    operations = [
    ]
