# Generated by Django 3.0.5 on 2020-05-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0016_auto_20200524_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ccomments', to='firstApp.Post'),
        ),
    ]
