# Generated by Django 3.0.5 on 2020-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_ccomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccomment',
            name='post',
        ),
    ]
