# Generated by Django 3.0.5 on 2020-05-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_remove_ccomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ccomments', to='firstApp.Post'),
        ),
    ]
