# Generated by Django 3.0.5 on 2020-05-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0020_auto_20200526_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstApp.ClassDate'),
        ),
    ]
