# Generated by Django 3.0.5 on 2020-05-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0021_auto_20200526_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_date', to='firstApp.ClassDate'),
        ),
    ]
